function [R, dR, J] = FastBoundaryShape(GeometryObj,IntegrationPoint,...
                global_basis_index,element_local_mapping,element_ranges, ...
                e, Boundary)
            switch GeometryObj.type
                case 'curve'
                    [R, dR, J] = FastBoundaryShape1D(GeometryObj, ...
                        IntegrationPoint,global_basis_index, ...
                        element_local_mapping,element_ranges,e, Boundary);
                case 'surf'
                    [R, dR, J] = FastBoundaryShape2D(GeometryObj, ...
                        IntegrationPoint,global_basis_index, ...
                        element_local_mapping,element_ranges,e, Boundary);
                case 'volume'
                    [R, dR, J] = FastBoundaryShape3D(GeometryObj, ...
                        IntegrationPoint,global_basis_index, ...
                        element_local_mapping,element_ranges,e, Boundary);
            end
            
end