function [R, dR, J] = FastShape(GeometryObject,IntegrationPoint, ...
    global_basis_index,element_local_mapping,element_ranges,element)
    switch GeometryObject.type
        case 'curve'
            [R, dR, J] = FastShape1D(GeometryObject,IntegrationPoint, ...
                global_basis_index,element_local_mapping,element_ranges,...
                element) ;
        case 'surf'
            [R, dR, J] = FastShape2D(GeometryObject,IntegrationPoint, ... 
                global_basis_index, element_local_mapping, element_ranges, ...
                element);
        case 'volume'
            [R, dR, J] = FastShape3D(GeometryObject,IntegrationPoint, ... 
                global_basis_index, element_local_mapping, element_ranges, ...
                element);
    end
end